[build]
base = "/"
deps = "pip install -r requirements.txt"
command = "python manage.py collectstatic --noinput"
publish = "staticfiles"

[build.environment]
PYTHON_VERSION = "3.11"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
framework = "django"
targetPort = 8000
