[build]
command = "python manage.py collectstatic --noinput && python manage.py migrate"
publish = "staticfiles"
functions = "netlify/functions"

[build.environment]
PYTHON_VERSION = "3.9"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
framework = "django"
targetPort = 8000
